version: '3'
services:
  docker-backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000

  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin